In [ ]:
import pandas as pd

In [ ]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [ ]:
print("Train shape: ", train.shape)
print("Test shape: ", test.shape)

Train shape:  (439140, 16)
Test shape:  (188165, 15)

In [ ]:
print("\nTrain Colomns: \n")
print(train.columns.tolist())
print("\nTest Colomns: \n")
print(test.columns.tolist())

Train Colomns:

['id', 'Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', 'Position_Change', 'PitNextLap']

Test Colomns:

['id', 'Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', 'Position_Change']

In [ ]:
print("\nFirst 5 Rows:\n")
print(train.head())

First 5 Rows:

   id Driver Compound                   Race  Year  PitStop  LapNumber  Stint  \
0   0   D109     HARD    Canadian Grand Prix  2022        0         50      2
1   1   D086     HARD       Dutch Grand Prix  2025        1         27      2
2   2    ZON     HARD    Austrian Grand Prix  2022        0         59      3
3   3    SPE   MEDIUM     Pre-Season Testing  2023        0          2      1
4   4   D019     HARD  Azerbaijan Grand Prix  2022        1         26      3

   TyreLife  Position  LapTime (s)  LapTime_Delta  Cumulative_Degradation  \
0      39.0         8       78.491         -7.564                  21.019
1       7.0         4       75.095        -32.617                -223.207
2      22.0        13       70.945         -7.540                -100.529
3       2.0         7       94.361         -7.324                  -7.324
4       6.0         2      107.878          8.965                 -14.139

   RaceProgress  Position_Change  PitNextLap
0      0.714286              5.0         1.0
1      0.346154             -3.0         0.0
2      0.819444              3.0         1.0
3      0.076923              0.0         0.0
4      0.361111              3.0         0.0

In [ ]:
print("\nInfo:\n")
print(train.info())

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  object
 2   Compound                439140 non-null  object
 3   Race                    439140 non-null  object
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 53.6+ MB
None

In [ ]:
print(train["PitNextLap"].value_counts())
print("\n Normalized: \n")
print(train["PitNextLap"].value_counts(normalize=True))

PitNextLap
0.0    351759
1.0     87381
Name: count, dtype: int64

 Normalized:

PitNextLap
0.0    0.801018
1.0    0.198982
Name: proportion, dtype: float64

In [ ]:
print(train["Race"].nunique())
print(train["Driver"].nunique())

print(train.groupby("Race").size().head())
print(train.groupby("Driver").size().head())

26
887
Race
Abu Dhabi Grand Prix     16427
Australian Grand Prix    18406
Austrian Grand Prix      21223
Azerbaijan Grand Prix    12126
Bahrain Grand Prix       19535
dtype: int64
Driver
ALB    1346
ALE    1451
ALG    1527
ALO    1386
AND    1461
dtype: int64

In [ ]:
numeric_cols = ['PitStop', 'LapNumber', 'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', 'Position_Change']
train[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
PitStop,439140.0,0.136118,0.342915,0.000000,0.00000,0.000000,0.000000,1.000
LapNumber,439140.0,23.105909,16.958261,1.000000,9.00000,19.000000,36.000000,78.000
Stint,439140.0,1.789113,0.950194,1.000000,1.00000,2.000000,2.000000,8.000
TyreLife,439140.0,14.158231,9.801338,1.000000,6.00000,12.000000,20.000000,77.000
Position,439140.0,9.630339,5.278770,1.000000,5.00000,10.000000,14.000000,20.000
LapTime (s),439140.0,90.948735,19.772769,67.694000,82.62100,90.521000,98.471000,2507.607
LapTime_Delta,439140.0,-3.770040,43.945759,-2403.895000,-8.88400,-0.295000,0.115000,2423.932
Cumulative_Degradation,439140.0,-25.721759,54.766573,-274.564000,-46.56625,-20.994000,-6.199000,2412.026
RaceProgress,439140.0,0.337661,0.253277,0.012821,0.12987,0.269231,0.513158,1.000
Position_Change,439140.0,0.101542,4.006765,-18.000000,-1.00000,0.000000,2.000000,18.000

In [ ]:
train.groupby("PitNextLap")[[
    "TyreLife",
    "LapNumber",
    "LapTime (s)",
    "LapTime_Delta",
    "Cumulative_Degradation",
    "RaceProgress",
    "Position"
]].mean()

,TyreLife,LapNumber,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position
PitNextLap,,,,,,,
0.0,12.822114,20.848706,91.284747,-3.661698,-21.152364,0.314247,9.574172
1.0,19.536873,32.192456,89.596092,-4.206182,-44.116212,0.431914,9.856445

In [ ]:
train.groupby(["Race","Driver"]).size().describe()

count    14942.00000
mean        29.38964
std         24.03104
min          1.00000
25%          5.00000
50%         25.00000
75%         50.00000
max        103.00000
dtype: float64

In [ ]:
from sklearn.model_selection import GroupKFold
groups = train["Race"] + "_" + train["Driver"]
print(groups.head())

0      Canadian Grand Prix_D109
1         Dutch Grand Prix_D086
2       Austrian Grand Prix_ZON
3        Pre-Season Testing_SPE
4    Azerbaijan Grand Prix_D019
dtype: object

In [ ]:
!pip install catboost -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.0 MB/s eta 0:00:00

In [ ]:
from catboost import CatBoostClassifier
from sklearn.model_selection import GroupKFold
from sklearn.metrics import roc_auc_score
import numpy as np

In [ ]:
train = train.dropna(subset=["PitNextLap"])

In [ ]:
print(train["PitNextLap"].isna().sum())

0

In [ ]:
target = "PitNextLap"
features = [col for col in train.columns if col not in ["id",target]]
X = train[features]
y = train[target]
categorical_features = ["Driver", "Compound", "Race"]
print(features)

['Driver', 'Compound', 'Race', 'Year', 'PitStop', 'LapNumber', 'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', 'Position_Change']

In [ ]:
gkf = GroupKFold(n_splits=5)

scores = []

for fold, (train_idx, valid_idx) in enumerate(
    gkf.split(X, y, groups)
):

    print(f"\n========== FOLD {fold + 1} ==========")

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        eval_metric="AUC",
        verbose=100
    )

    model.fit(
        X_train,
        y_train,
        cat_features=categorical_features,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )

    preds = model.predict_proba(X_valid)[:, 1]

    auc = roc_auc_score(y_valid, preds)

    print(f"Fold AUC: {auc}")

    scores.append(auc)

print("\n========== RESULTS ==========")
print("Mean AUC:", np.mean(scores))
print("Std AUC:", np.std(scores))

========== FOLD 1 ==========
0:	test: 0.8965392	best: 0.8965392 (0)	total: 841ms	remaining: 6m 59s
100:	test: 0.9289407	best: 0.9289407 (100)	total: 40.5s	remaining: 2m 40s
200:	test: 0.9359243	best: 0.9359243 (200)	total: 1m 17s	remaining: 1m 55s
300:	test: 0.9391536	best: 0.9391536 (300)	total: 1m 54s	remaining: 1m 15s
400:	test: 0.9410839	best: 0.9410839 (400)	total: 2m 31s	remaining: 37.3s
499:	test: 0.9423661	best: 0.9423661 (499)	total: 3m 7s	remaining: 0us

bestTest = 0.9423660869
bestIteration = 499

Fold AUC: 0.9423660869037664

========== FOLD 2 ==========
0:	test: 0.8978491	best: 0.8978491 (0)	total: 328ms	remaining: 2m 43s
100:	test: 0.9296477	best: 0.9296477 (100)	total: 39.3s	remaining: 2m 35s
200:	test: 0.9361201	best: 0.9361201 (200)	total: 1m 16s	remaining: 1m 53s
300:	test: 0.9392822	best: 0.9392822 (300)	total: 1m 52s	remaining: 1m 14s
400:	test: 0.9412469	best: 0.9412469 (400)	total: 2m 28s	remaining: 36.6s
499:	test: 0.9425460	best: 0.9425460 (499)	total: 3m 4s	remaining: 0us

bestTest = 0.9425459577
bestIteration = 499

Fold AUC: 0.9425459576952926

========== FOLD 3 ==========
0:	test: 0.8967178	best: 0.8967178 (0)	total: 318ms	remaining: 2m 38s
100:	test: 0.9278366	best: 0.9278366 (100)	total: 38s	remaining: 2m 29s
200:	test: 0.9344264	best: 0.9344264 (200)	total: 1m 15s	remaining: 1m 51s
300:	test: 0.9381572	best: 0.9381572 (300)	total: 1m 51s	remaining: 1m 13s
400:	test: 0.9402076	best: 0.9402076 (400)	total: 2m 28s	remaining: 36.6s
499:	test: 0.9416192	best: 0.9416192 (499)	total: 3m 2s	remaining: 0us

bestTest = 0.9416191732
bestIteration = 499

Fold AUC: 0.9416191732229942

========== FOLD 4 ==========
0:	test: 0.8952926	best: 0.8952926 (0)	total: 350ms	remaining: 2m 54s
100:	test: 0.9271028	best: 0.9271028 (100)	total: 38.1s	remaining: 2m 30s
200:	test: 0.9338572	best: 0.9338572 (200)	total: 1m 15s	remaining: 1m 51s
300:	test: 0.9371184	best: 0.9371184 (300)	total: 1m 51s	remaining: 1m 14s
400:	test: 0.9392720	best: 0.9392720 (400)	total: 2m 28s	remaining: 36.6s
499:	test: 0.9407154	best: 0.9407154 (499)	total: 3m 4s	remaining: 0us

bestTest = 0.9407154446
bestIteration = 499

Fold AUC: 0.9407154446383319

========== FOLD 5 ==========
0:	test: 0.8985135	best: 0.8985135 (0)	total: 583ms	remaining: 4m 50s
100:	test: 0.9292140	best: 0.9292140 (100)	total: 40.3s	remaining: 2m 39s
200:	test: 0.9352923	best: 0.9352923 (200)	total: 1m 17s	remaining: 1m 55s
300:	test: 0.9387948	best: 0.9387948 (300)	total: 1m 55s	remaining: 1m 16s
400:	test: 0.9407158	best: 0.9407158 (400)	total: 2m 32s	remaining: 37.6s
499:	test: 0.9418390	best: 0.9418390 (499)	total: 3m 8s	remaining: 0us

bestTest = 0.9418389921
bestIteration = 499

Fold AUC: 0.9418389921466672

========== RESULTS ==========
Mean AUC: 0.9418171309214104
Std AUC: 0.0006458976647654518

In [ ]:
feature_importance = model.get_feature_importance()

importance_df = pd.DataFrame({
    "Feature": features,
    "Importance": feature_importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(importance_df)

                   Feature  Importance
3                     Year   53.324442
6                    Stint   13.946022
7                 TyreLife   10.008146
10           LapTime_Delta    4.668112
12            RaceProgress    3.661960
2                     Race    3.547959
1                 Compound    3.082758
5                LapNumber    1.484803
13         Position_Change    1.380602
11  Cumulative_Degradation    1.152756
0                   Driver    0.987064
8                 Position    0.951326
4                  PitStop    0.919200
9              LapTime (s)    0.884851

In [ ]:
train.groupby("Year")["PitNextLap"].mean()
train.groupby("Year").size()

Year
2022     82989
2023    136147
2024    127110
2025     92894
dtype: int64

In [ ]:
train.groupby("Year")["PitNextLap"].mean()

Year
2022    0.266505
2023    0.009607
2024    0.295319
2025    0.284389
Name: PitNextLap, dtype: float64

In [ ]:
features_no_year = [
    col for col in features if col != "Year"
]

X_no_year = train[features_no_year]

In [ ]:
gkf = GroupKFold(n_splits=5)

scores_no_year = []

for fold, (train_idx, valid_idx) in enumerate(
    gkf.split(X_no_year, y, groups)
):

    print(f"\n========== FOLD {fold+1} ==========")

    X_train = X_no_year.iloc[train_idx]
    X_valid = X_no_year.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        eval_metric="AUC",
        verbose=0
    )

    model.fit(
        X_train,
        y_train,
        cat_features=["Driver", "Compound", "Race"],
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )

    preds = model.predict_proba(X_valid)[:, 1]

    auc = roc_auc_score(y_valid, preds)

    print("Fold AUC:", auc)

    scores_no_year.append(auc)

print("\nMean AUC:", np.mean(scores_no_year))
print("Std AUC:", np.std(scores_no_year))

========== FOLD 1 ==========
Fold AUC: 0.9369122690992188

========== FOLD 2 ==========
Fold AUC: 0.9361586702793654

========== FOLD 3 ==========
Fold AUC: 0.9354992663084274

========== FOLD 4 ==========
Fold AUC: 0.9344835648424009

========== FOLD 5 ==========
Fold AUC: 0.935677011932653

Mean AUC: 0.9357461564924131
Std AUC: 0.0007987314497314141

Training using Year in categorical feature

In [ ]:
final_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    eval_metric="AUC",
    verbose=100
)

final_model.fit(
    X,
    y,
    cat_features=categorical_features
)

0:	total: 404ms	remaining: 3m 21s
100:	total: 43.3s	remaining: 2m 51s
200:	total: 1m 25s	remaining: 2m 6s
300:	total: 2m 6s	remaining: 1m 23s
400:	total: 2m 46s	remaining: 41.2s
499:	total: 3m 26s	remaining: 0us

CatBoostClassifier(depth=6, eval_metric='AUC', iterations=500, learning_rate=0.05, verbose=100)

In [ ]:
X_test = test[features]

test_preds = final_model.predict_proba(X_test)[:, 1]

In [ ]:
submission = pd.DataFrame({
    "id": test["id"],
    "PitNextLap": test_preds
})

submission.to_csv("submission.csv", index=False)

submission.head()

       id  PitNextLap
0  439140    0.005620
1  439141    0.007515
2  439142    0.006148
3  439143    0.101929
4  439144    0.757827

In [ ]:
from google.colab import files

files.download("submission.csv")

In [ ]:
train.shape
test.shape
submission.shape

(188165, 2)